[[redirects]]
from   = "https://www.commongroundhelps.org/static/media/2016-17_annual_report_Common_Ground.59a71054.pdf"
to     = "https://www.commongroundhelps.org/static/media/2016-17_Common_Ground_Annual_Report-Corrected.f1b5ace5.pdf"
status = 200
